@startuml
title Container diagram «Interhet Bank»

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "User of the «Interhet Bank» system")
System(InterhetBankSystem, "«Interhet Bank» System")

Container_Boundary(InterhetBankSystem, "Interhet bank system") {
  Container(WebApp, "Web Application", "Spring", "Handles user interactions")
  Container(MobileApp, "Mobile Application", "Spring", "Handles user interactions")

  Container(APIGateway, "API Gateway")

  Container(UserProfileService, "User profile Service", "Spring")
  Container(AuthorizationService, "Authorization Service", "Spring")
  Container(DepositService, "Deposit Service", "Spring")
  Container(PaymentService, "Payment Service", "Spring")
  Container(EventsService, "Events Service", "kafka")

  Container(Payment_Database, "Payment Database", "PostgreSQL", "Stores payment data")
  Container(User_Database, "User Database", "PostgreSQL", "Stores authorization data")
  Container(Deposit_Database, "Deposi Database", "PostgreSQL", "Stores deposit data")
}

Rel(user, WebApp,)
Rel(user, MobileApp,)

System_Ext(bank, "Bank System", "External bank for processing payments")
System_Ext(api_abs, "ABS API")


Rel(WebApp, APIGateway ,"API Gateway requests")
Rel(MobileApp, APIGateway ,"API Gateway requests")

Rel(APIGateway,UserProfileService,"Processes client profile requests")
Rel(APIGateway,AuthorizationService,"Processes authorization and identification requests")
Rel(APIGateway,DepositService,"Processes requests deposit")
Rel(APIGateway,PaymentService,"Processes payment requests")

Rel(PaymentService, Payment_Database,"Reads/Writes payment data")
Rel(PaymentService,bank,"Processes payments")
Rel(PaymentService,EventsService,"read/write events")
Rel(DepositService,EventsService,"read/write events")
Rel(AuthorizationService, User_Database,"Reads/Writes authorization data")
Rel(UserProfileService, User_Database,"Reads/Writes user profile data")
Rel(DepositService, Deposit_Database,"Reads/Writes deposit data")
Rel(DepositService, api_abs, "Processes deposits")
@enduml